-- vim.o.background = "dark"
-- vim.g.gruvbox_material_background = "hard"
-- vim.g.gruvbox_material_better_performance = 1
-- vim.cmd("colorscheme gruvbox-material")
-- vim.g.gruvbox_flat_background = "hard"
-- vim.g.gruvbox_flat_better_performance = 1
--
-- vim.g.gruvbox_flat_style = "dark"
--
-- vim.g.gruvbox_italic_comments = false
-- vim.g.gruvbox_italic_keywords = false
--
-- vim.cmd("colorscheme gruvbox-flat")
--
--
-- moved this line to bufferline.lua
-- because the sequnce will affect the bufferline color
-- vim.cmd[[colorscheme tokyonight]]
